from __future__ import annotations

import re


COUNTRY_ALIASES: dict[str, str] = {
    "ad": "AD",
    "andorra": "AD",
    "ae": "AE",
    "united arab emirates": "AE",
    "uae": "AE",
    "af": "AF",
    "afghanistan": "AF",
    "ag": "AG",
    "antigua and barbuda": "AG",
    "ai": "AI",
    "anguilla": "AI",
    "al": "AL",
    "albania": "AL",
    "am": "AM",
    "armenia": "AM",
    "ao": "AO",
    "angola": "AO",
    "ar": "AR",
    "argentina": "AR",
    "as": "AS",
    "american samoa": "AS",
    "at": "AT",
    "austria": "AT",
    "au": "AU",
    "australia": "AU",
    "aw": "AW",
    "aruba": "AW",
    "ax": "AX",
    "aland islands": "AX",
    "aland": "AX",
    "az": "AZ",
    "azerbaijan": "AZ",
    "ba": "BA",
    "bosnia and herzegovina": "BA",
    "bb": "BB",
    "barbados": "BB",
    "bd": "BD",
    "bangladesh": "BD",
    "be": "BE",
    "belgium": "BE",
    "bf": "BF",
    "burkina faso": "BF",
    "bg": "BG",
    "bulgaria": "BG",
    "bh": "BH",
    "bahrain": "BH",
    "bi": "BI",
    "burundi": "BI",
    "bj": "BJ",
    "benin": "BJ",
    "bl": "BL",
    "saint barthelemy": "BL",
    "saint barts": "BL",
    "bm": "BM",
    "bermuda": "BM",
    "bn": "BN",
    "brunei": "BN",
    "brunei darussalam": "BN",
    "bo": "BO",
    "bolivia": "BO",
    "bolivia plurinational state of": "BO",
    "bq": "BQ",
    "bonaire": "BQ",
    "bonaire sint eustatius and saba": "BQ",
    "br": "BR",
    "brazil": "BR",
    "bs": "BS",
    "bahamas": "BS",
    "bt": "BT",
    "bhutan": "BT",
    "bw": "BW",
    "botswana": "BW",
    "by": "BY",
    "belarus": "BY",
    "bz": "BZ",
    "belize": "BZ",
    "ca": "CA",
    "canada": "CA",
    "cc": "CC",
    "cocos islands": "CC",
    "cocos keeling islands": "CC",
    "cd": "CD",
    "congo kinshasa": "CD",
    "democratic republic of the congo": "CD",
    "congo democratic republic": "CD",
    "cf": "CF",
    "central african republic": "CF",
    "cg": "CG",
    "congo": "CG",
    "republic of the congo": "CG",
    "congo brazzaville": "CG",
    "ch": "CH",
    "switzerland": "CH",
    "ci": "CI",
    "cote d ivoire": "CI",
    "cote divoire": "CI",
    "ivory coast": "CI",
    "ck": "CK",
    "cook islands": "CK",
    "cl": "CL",
    "chile": "CL",
    "cm": "CM",
    "cameroon": "CM",
    "cn": "CN",
    "china": "CN",
    "co": "CO",
    "colombia": "CO",
    "cr": "CR",
    "costa rica": "CR",
    "cu": "CU",
    "cuba": "CU",
    "cv": "CV",
    "cape verde": "CV",
    "cabo verde": "CV",
    "cw": "CW",
    "curacao": "CW",
    "cx": "CX",
    "christmas island": "CX",
    "cy": "CY",
    "cyprus": "CY",
    "cz": "CZ",
    "czech republic": "CZ",
    "czechia": "CZ",
    "de": "DE",
    "germany": "DE",
    "dj": "DJ",
    "djibouti": "DJ",
    "dk": "DK",
    "denmark": "DK",
    "dm": "DM",
    "dominica": "DM",
    "do": "DO",
    "dominican republic": "DO",
    "dz": "DZ",
    "algeria": "DZ",
    "ec": "EC",
    "ecuador": "EC",
    "ee": "EE",
    "estonia": "EE",
    "eg": "EG",
    "egypt": "EG",
    "eh": "EH",
    "western sahara": "EH",
    "er": "ER",
    "eritrea": "ER",
    "es": "ES",
    "spain": "ES",
    "et": "ET",
    "ethiopia": "ET",
    "fi": "FI",
    "finland": "FI",
    "fj": "FJ",
    "fiji": "FJ",
    "fk": "FK",
    "falkland islands": "FK",
    "fm": "FM",
    "micronesia": "FM",
    "federated states of micronesia": "FM",
    "fo": "FO",
    "faroe islands": "FO",
    "fr": "FR",
    "france": "FR",
    "ga": "GA",
    "gabon": "GA",
    "gb": "GB",
    "uk": "GB",
    "united kingdom": "GB",
    "great britain": "GB",
    "britain": "GB",
    "england": "GB",
    "scotland": "GB",
    "wales": "GB",
    "northern ireland": "GB",
    "gd": "GD",
    "grenada": "GD",
    "ge": "GE",
    "georgia": "GE",
    "gf": "GF",
    "french guiana": "GF",
    "gg": "GG",
    "guernsey": "GG",
    "gh": "GH",
    "ghana": "GH",
    "gi": "GI",
    "gibraltar": "GI",
    "gl": "GL",
    "greenland": "GL",
    "gm": "GM",
    "gambia": "GM",
    "gn": "GN",
    "guinea": "GN",
    "gp": "GP",
    "guadeloupe": "GP",
    "gq": "GQ",
    "equatorial guinea": "GQ",
    "gr": "GR",
    "greece": "GR",
    "gt": "GT",
    "guatemala": "GT",
    "gu": "GU",
    "guam": "GU",
    "gw": "GW",
    "guinea bissau": "GW",
    "gy": "GY",
    "guyana": "GY",
    "hk": "HK",
    "hong kong": "HK",
    "hm": "HM",
    "heard island and mcdonald islands": "HM",
    "hn": "HN",
    "honduras": "HN",
    "hr": "HR",
    "croatia": "HR",
    "ht": "HT",
    "haiti": "HT",
    "hu": "HU",
    "hungary": "HU",
    "id": "ID",
    "indonesia": "ID",
    "ie": "IE",
    "ireland": "IE",
    "il": "IL",
    "israel": "IL",
    "im": "IM",
    "isle of man": "IM",
    "in": "IN",
    "india": "IN",
    "io": "IO",
    "british indian ocean territory": "IO",
    "iq": "IQ",
    "iraq": "IQ",
    "ir": "IR",
    "iran": "IR",
    "iran islamic republic of": "IR",
    "is": "IS",
    "iceland": "IS",
    "it": "IT",
    "italy": "IT",
    "je": "JE",
    "jersey": "JE",
    "jm": "JM",
    "jamaica": "JM",
    "jo": "JO",
    "jordan": "JO",
    "jp": "JP",
    "japan": "JP",
    "ke": "KE",
    "kenya": "KE",
    "kg": "KG",
    "kyrgyzstan": "KG",
    "kh": "KH",
    "cambodia": "KH",
    "ki": "KI",
    "kiribati": "KI",
    "km": "KM",
    "comoros": "KM",
    "kn": "KN",
    "saint kitts and nevis": "KN",
    "kp": "KP",
    "north korea": "KP",
    "korea democratic peoples republic of": "KP",
    "kr": "KR",
    "south korea": "KR",
    "korea republic of": "KR",
    "kw": "KW",
    "kuwait": "KW",
    "ky": "KY",
    "cayman islands": "KY",
    "kz": "KZ",
    "kazakhstan": "KZ",
    "la": "LA",
    "laos": "LA",
    "lao peoples democratic republic": "LA",
    "lb": "LB",
    "lebanon": "LB",
    "lc": "LC",
    "saint lucia": "LC",
    "li": "LI",
    "liechtenstein": "LI",
    "lk": "LK",
    "sri lanka": "LK",
    "lr": "LR",
    "liberia": "LR",
    "ls": "LS",
    "lesotho": "LS",
    "lt": "LT",
    "lithuania": "LT",
    "lu": "LU",
    "luxembourg": "LU",
    "lv": "LV",
    "latvia": "LV",
    "ly": "LY",
    "libya": "LY",
    "ma": "MA",
    "morocco": "MA",
    "mc": "MC",
    "monaco": "MC",
    "md": "MD",
    "moldova": "MD",
    "moldova republic of": "MD",
    "me": "ME",
    "montenegro": "ME",
    "mf": "MF",
    "saint martin": "MF",
    "mg": "MG",
    "madagascar": "MG",
    "mh": "MH",
    "marshall islands": "MH",
    "mk": "MK",
    "north macedonia": "MK",
    "macedonia": "MK",
    "ml": "ML",
    "mali": "ML",
    "mm": "MM",
    "myanmar": "MM",
    "burma": "MM",
    "mn": "MN",
    "mongolia": "MN",
    "mo": "MO",
    "macao": "MO",
    "macau": "MO",
    "mp": "MP",
    "northern mariana islands": "MP",
    "mq": "MQ",
    "martinique": "MQ",
    "mr": "MR",
    "mauritania": "MR",
    "ms": "MS",
    "montserrat": "MS",
    "mt": "MT",
    "malta": "MT",
    "mu": "MU",
    "mauritius": "MU",
    "mv": "MV",
    "maldives": "MV",
    "mw": "MW",
    "malawi": "MW",
    "mx": "MX",
    "mexico": "MX",
    "my": "MY",
    "malaysia": "MY",
    "mz": "MZ",
    "mozambique": "MZ",
    "na": "NA",
    "namibia": "NA",
    "nc": "NC",
    "new caledonia": "NC",
    "ne": "NE",
    "niger": "NE",
    "nf": "NF",
    "norfolk island": "NF",
    "ng": "NG",
    "nigeria": "NG",
    "ni": "NI",
    "nicaragua": "NI",
    "nl": "NL",
    "netherlands": "NL",
    "no": "NO",
    "norway": "NO",
    "np": "NP",
    "nepal": "NP",
    "nr": "NR",
    "nauru": "NR",
    "nu": "NU",
    "niue": "NU",
    "nz": "NZ",
    "new zealand": "NZ",
    "om": "OM",
    "oman": "OM",
    "pa": "PA",
    "panama": "PA",
    "pe": "PE",
    "peru": "PE",
    "pf": "PF",
    "french polynesia": "PF",
    "pg": "PG",
    "papua new guinea": "PG",
    "ph": "PH",
    "philippines": "PH",
    "pk": "PK",
    "pakistan": "PK",
    "pl": "PL",
    "poland": "PL",
    "pm": "PM",
    "saint pierre and miquelon": "PM",
    "pn": "PN",
    "pitcairn": "PN",
    "pr": "PR",
    "puerto rico": "PR",
    "ps": "PS",
    "palestine": "PS",
    "palestinian territory": "PS",
    "state of palestine": "PS",
    "pt": "PT",
    "portugal": "PT",
    "pw": "PW",
    "palau": "PW",
    "py": "PY",
    "paraguay": "PY",
    "qa": "QA",
    "qatar": "QA",
    "re": "RE",
    "reunion": "RE",
    "ro": "RO",
    "romania": "RO",
    "rs": "RS",
    "serbia": "RS",
    "ru": "RU",
    "russia": "RU",
    "russian federation": "RU",
    "rw": "RW",
    "rwanda": "RW",
    "sa": "SA",
    "saudi arabia": "SA",
    "sb": "SB",
    "solomon islands": "SB",
    "sc": "SC",
    "seychelles": "SC",
    "sd": "SD",
    "sudan": "SD",
    "se": "SE",
    "sweden": "SE",
    "sg": "SG",
    "singapore": "SG",
    "sh": "SH",
    "saint helena": "SH",
    "si": "SI",
    "slovenia": "SI",
    "sj": "SJ",
    "svalbard and jan mayen": "SJ",
    "sk": "SK",
    "slovakia": "SK",
    "sl": "SL",
    "sierra leone": "SL",
    "sm": "SM",
    "san marino": "SM",
    "sn": "SN",
    "senegal": "SN",
    "so": "SO",
    "somalia": "SO",
    "sr": "SR",
    "suriname": "SR",
    "ss": "SS",
    "south sudan": "SS",
    "st": "ST",
    "sao tome and principe": "ST",
    "sv": "SV",
    "el salvador": "SV",
    "sx": "SX",
    "sint maarten": "SX",
    "sy": "SY",
    "syria": "SY",
    "syrian arab republic": "SY",
    "sz": "SZ",
    "eswatini": "SZ",
    "swaziland": "SZ",
    "tc": "TC",
    "turks and caicos islands": "TC",
    "td": "TD",
    "chad": "TD",
    "tf": "TF",
    "french southern territories": "TF",
    "tg": "TG",
    "togo": "TG",
    "th": "TH",
    "thailand": "TH",
    "tj": "TJ",
    "tajikistan": "TJ",
    "tk": "TK",
    "tokelau": "TK",
    "tl": "TL",
    "timor leste": "TL",
    "east timor": "TL",
    "tm": "TM",
    "turkmenistan": "TM",
    "tn": "TN",
    "tunisia": "TN",
    "to": "TO",
    "tonga": "TO",
    "tr": "TR",
    "turkey": "TR",
    "turkiye": "TR",
    "tt": "TT",
    "trinidad and tobago": "TT",
    "tv": "TV",
    "tuvalu": "TV",
    "tw": "TW",
    "taiwan": "TW",
    "taiwan province of china": "TW",
    "tz": "TZ",
    "tanzania": "TZ",
    "united republic of tanzania": "TZ",
    "ua": "UA",
    "ukraine": "UA",
    "ug": "UG",
    "uganda": "UG",
    "um": "UM",
    "united states minor outlying islands": "UM",
    "us": "US",
    "usa": "US",
    "united states": "US",
    "united states of america": "US",
    "uy": "UY",
    "uruguay": "UY",
    "uz": "UZ",
    "uzbekistan": "UZ",
    "va": "VA",
    "vatican": "VA",
    "holy see": "VA",
    "vc": "VC",
    "saint vincent and the grenadines": "VC",
    "ve": "VE",
    "venezuela": "VE",
    "venezuela bolivarian republic of": "VE",
    "vg": "VG",
    "british virgin islands": "VG",
    "vi": "VI",
    "us virgin islands": "VI",
    "virgin islands us": "VI",
    "vn": "VN",
    "vietnam": "VN",
    "viet nam": "VN",
    "vu": "VU",
    "vanuatu": "VU",
    "wf": "WF",
    "wallis and futuna": "WF",
    "ws": "WS",
    "samoa": "WS",
    "ye": "YE",
    "yemen": "YE",
    "yt": "YT",
    "mayotte": "YT",
    "za": "ZA",
    "south africa": "ZA",
    "zm": "ZM",
    "zambia": "ZM",
    "zw": "ZW",
    "zimbabwe": "ZW",
}


def normalize_country(value: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", " ", value.strip().lower()).strip()
    if not normalized:
        return ""
    country_code = COUNTRY_ALIASES.get(normalized)
    if not country_code:
        raise ValueError(
            "Invalid search_country value: "
            f"{value!r}. Use a 2-letter country code like 'SG' or a full country name like 'Singapore'."
        )
    return country_code
